package org.sohagroup.crmconnector.domain.crm.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.1 2021-01-05T18:53:52.779+03:30 Generated source version: 3.4.1
 */
@WebService(targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", name = "IOrganizationService")
@XmlSeeAlso({ObjectFactory.class})
public interface IOrganizationService {

    @WebMethod(operationName = "Disassociate", action = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Disassociate")
    @Action(input = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Disassociate", output = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/DisassociateResponse", fault = {
        @FaultAction(className = IOrganizationServiceDisassociateOrganizationServiceFaultFaultFaultMessage.class, value = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/DisassociateOrganizationServiceFaultFault")})
    @RequestWrapper(localName = "Disassociate", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "org.sohagroup.crmconnector.domain.crm.model.Disassociate")
    @ResponseWrapper(localName = "DisassociateResponse", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "org.sohagroup.crmconnector.domain.crm.model.DisassociateResponse")
    void disassociate(

        @WebParam(name = "entityName", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
            String entityName,
        @WebParam(name = "entityId", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
            String entityId,
        @WebParam(name = "relationship", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
            Relationship relationship,
        @WebParam(name = "relatedEntities", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
            org.sohagroup.crmconnector.domain.crm.model.EntityReferenceCollection relatedEntities
    ) throws IOrganizationServiceDisassociateOrganizationServiceFaultFaultFaultMessage;

    @WebMethod(operationName = "RetrieveMultiple", action = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/RetrieveMultiple")
    @Action(input = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/RetrieveMultiple", output = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/RetrieveMultipleResponse", fault = {
        @FaultAction(className = IOrganizationServiceRetrieveMultipleOrganizationServiceFaultFaultFaultMessage.class, value = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/RetrieveMultipleOrganizationServiceFaultFault")})
    @RequestWrapper(localName = "RetrieveMultiple", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "org.sohagroup.crmconnector.domain.crm.model.RetrieveMultiple")
    @ResponseWrapper(localName = "RetrieveMultipleResponse", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "org.sohagroup.crmconnector.domain.crm.model.RetrieveMultipleResponse")
    @WebResult(name = "RetrieveMultipleResult", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
    EntityCollection retrieveMultiple(

        @WebParam(name = "query", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
            QueryBase query
    ) throws IOrganizationServiceRetrieveMultipleOrganizationServiceFaultFaultFaultMessage;

    @WebMethod(operationName = "Update", action = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Update")
    @Action(input = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Update", output = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/UpdateResponse", fault = {
        @FaultAction(className = IOrganizationServiceUpdateOrganizationServiceFaultFaultFaultMessage.class, value = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/UpdateOrganizationServiceFaultFault")})
    @RequestWrapper(localName = "Update", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "org.sohagroup.crmconnector.domain.crm.model.Update")
    @ResponseWrapper(localName = "UpdateResponse", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "org.sohagroup.crmconnector.domain.crm.model.UpdateResponse")
    void update(

        @WebParam(name = "entity", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
            Entity entity
    ) throws IOrganizationServiceUpdateOrganizationServiceFaultFaultFaultMessage;

    @WebMethod(operationName = "Associate", action = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Associate")
    @Action(input = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Associate", output = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/AssociateResponse", fault = {
        @FaultAction(className = IOrganizationServiceAssociateOrganizationServiceFaultFaultFaultMessage.class, value = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/AssociateOrganizationServiceFaultFault")})
    @RequestWrapper(localName = "Associate", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "org.sohagroup.crmconnector.domain.crm.model.Associate")
    @ResponseWrapper(localName = "AssociateResponse", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "org.sohagroup.crmconnector.domain.crm.model.AssociateResponse")
    void associate(

        @WebParam(name = "entityName", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
            String entityName,
        @WebParam(name = "entityId", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
            String entityId,
        @WebParam(name = "relationship", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
            Relationship relationship,
        @WebParam(name = "relatedEntities", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
            org.sohagroup.crmconnector.domain.crm.model.EntityReferenceCollection relatedEntities
    ) throws IOrganizationServiceAssociateOrganizationServiceFaultFaultFaultMessage;

    @WebMethod(operationName = "Retrieve", action = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Retrieve")
    @Action(input = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Retrieve", output = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/RetrieveResponse", fault = {
        @FaultAction(className = IOrganizationServiceRetrieveOrganizationServiceFaultFaultFaultMessage.class, value = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/RetrieveOrganizationServiceFaultFault")})
    @RequestWrapper(localName = "Retrieve", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "org.sohagroup.crmconnector.domain.crm.model.Retrieve")
    @ResponseWrapper(localName = "RetrieveResponse", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "org.sohagroup.crmconnector.domain.crm.model.RetrieveResponse")
    @WebResult(name = "RetrieveResult", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
    Entity retrieve(

        @WebParam(name = "entityName", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
            String entityName,
        @WebParam(name = "id", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
            String id,
        @WebParam(name = "columnSet", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
            ColumnSet columnSet
    ) throws IOrganizationServiceRetrieveOrganizationServiceFaultFaultFaultMessage;

    @WebMethod(operationName = "Delete", action = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Delete")
    @Action(input = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Delete", output = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/DeleteResponse", fault = {
        @FaultAction(className = IOrganizationServiceDeleteOrganizationServiceFaultFaultFaultMessage.class, value = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/DeleteOrganizationServiceFaultFault")})
    @RequestWrapper(localName = "Delete", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "org.sohagroup.crmconnector.domain.crm.model.Delete")
    @ResponseWrapper(localName = "DeleteResponse", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "org.sohagroup.crmconnector.domain.crm.model.DeleteResponse")
    void delete(

        @WebParam(name = "entityName", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
            String entityName,
        @WebParam(name = "id", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
            String id
    ) throws IOrganizationServiceDeleteOrganizationServiceFaultFaultFaultMessage;

    @WebMethod(operationName = "Create", action = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Create")
    @Action(input = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Create", output = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/CreateResponse", fault = {
        @FaultAction(className = IOrganizationServiceCreateOrganizationServiceFaultFaultFaultMessage.class, value = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/CreateOrganizationServiceFaultFault")})
    @RequestWrapper(localName = "Create", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "org.sohagroup.crmconnector.domain.crm.model.Create")
    @ResponseWrapper(localName = "CreateResponse", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "org.sohagroup.crmconnector.domain.crm.model.CreateResponse")
    @WebResult(name = "CreateResult", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
    String create(

        @WebParam(name = "entity", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
            Entity entity
    ) throws IOrganizationServiceCreateOrganizationServiceFaultFaultFaultMessage;

    @WebMethod(operationName = "Execute", action = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Execute")
    @Action(input = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Execute", output = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/ExecuteResponse", fault = {
        @FaultAction(className = IOrganizationServiceExecuteOrganizationServiceFaultFaultFaultMessage.class, value = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/ExecuteOrganizationServiceFaultFault")})
    @RequestWrapper(localName = "Execute", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "org.sohagroup.crmconnector.domain.crm.model.Execute")
    @ResponseWrapper(localName = "ExecuteResponse", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "org.sohagroup.crmconnector.domain.crm.model.ExecuteResponse")
    @WebResult(name = "ExecuteResult", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
    org.sohagroup.crmconnector.domain.crm.model.OrganizationResponse execute(

        @WebParam(name = "request", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
            OrganizationRequest request
    ) throws IOrganizationServiceExecuteOrganizationServiceFaultFaultFaultMessage;
}
